apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: docker.io/forsrobin/backend_as_1
          ports:
            - containerPort: 3009
          env:
            - name: PORT
              value: "3009"

            - name: DATABASE_URL
              value: postgres://postgres:postgres@postgres-service:5432/a1?schema=public

            - name: CORS_ORIGIN
              value: http://localhost
